# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

# Nom du fichier du second disque
file_to_disk = 'disk2.vmdk'
# Taille du second disque en Go
disk_size = 20

Vagrant.configure(2) do |config|

  config.vm.provider "virtualbox" do |vb|
	vb.customize ["modifyvm", :id, "--memory", "2048", "--cpus", "1"]
	vb.customize ['createhd', '--filename', file_to_disk, '--size', disk_size * 1024]
	vb.customize ['storageattach', :id, '--storagectl', 'IDE Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', file_to_disk]
  end

  config.vm.box = "centos/7"
  config.vm.hostname = "sandbox-treeptik-centos"
  config.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)", type: "dhcp"
  config.vm.provision :shell, path: "bootstrap.sh"
end
